/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as verifierSol from './Verifier.sol/index.js';
export type { verifierSol };
export type { GoldenLock } from './GoldenLock.js';
export * as factories from './factories/index.js';
export type { IGroth16Verifier } from './Verifier.sol/IGroth16Verifier.js';
export { IGroth16Verifier__factory } from './factories/Verifier.sol/IGroth16Verifier__factory.js';
export type { Verifier } from './Verifier.sol/Verifier.js';
export { Verifier__factory } from './factories/Verifier.sol/Verifier__factory.js';
export { GoldenLock__factory } from './factories/GoldenLock__factory.js';