/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { Verifier, VerifierInterface } from "../../Verifier.sol/Verifier.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256[2]",
        "name": "a",
        "type": "uint256[2]"
      },
      {
        "internalType": "uint256[2][2]",
        "name": "b",
        "type": "uint256[2][2]"
      },
      {
        "internalType": "uint256[2]",
        "name": "c",
        "type": "uint256[2]"
      },
      {
        "internalType": "uint256[3]",
        "name": "input",
        "type": "uint256[3]"
      }
    ],
    "name": "verifyProof",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b5060f88061001c5f395ff3fe6080604052348015600e575f80fd5b50600436106026575f3560e01c806311479fea14602a575b5f80fd5b603f60353660046068565b6001949350505050565b604051901515815260200160405180910390f35b80604081018310156062575f80fd5b92915050565b5f805f80610160808688031215607c575f80fd5b608487876053565b945060c08601878111156095575f80fd5b60408701945060a388826053565b93505086818701111560b3575f80fd5b5092959194509261010001915056fea2646970667358221220dfe13ff8beea59a8298d4caea35d0f73662c77af930a174ae161c53190f8912264736f6c63430008180033";

  
      type VerifierConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: VerifierConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Verifier__factory extends ContractFactory {
    
      constructor(...args: VerifierConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Verifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Verifier__factory {
      return super.connect(runner) as Verifier__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): VerifierInterface {
      return new Interface(_abi) as VerifierInterface;
    }
    
    override attach(address: string | Addressable): Verifier {
      return super.attach(address) as Verifier;
    }
  static connect(address: string, runner?: ContractRunner | null): Verifier {
      return new Contract(address, _abi, runner) as unknown as Verifier;
    }
  }

  
  