/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace GoldenLock {
      
    export type EmergencyRequestStruct = {ambulanceOperator: AddressLike, hospital: AddressLike, ktasLevel: BigNumberish, requestedAt: BigNumberish, lockDeadline: BigNumberish, status: BigNumberish}

    export type EmergencyRequestStructOutput = [ambulanceOperator: string, hospital: string, ktasLevel: bigint, requestedAt: bigint, lockDeadline: bigint, status: bigint] & {ambulanceOperator: string, hospital: string, ktasLevel: bigint, requestedAt: bigint, lockDeadline: bigint, status: bigint }
  
    }

  export interface GoldenLockInterface extends Interface {
    getFunction(nameOrSignature: "GOLDEN_TIME_DURATION" | "availableSlots" | "cancelRequest" | "eip712Domain" | "expireIfOverdue" | "fulfillRequest" | "getRequest" | "hospitalVerifiers" | "isRegisteredHospital" | "isRequestActive" | "lockedSlots" | "nonces" | "owner" | "registerHospital" | "renounceOwnership" | "requestAndLock" | "requestCounter" | "requests" | "setTrustedRelayer" | "totalSlots" | "transferOwnership" | "trustedRelayer" | "usedRequestHash"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EIP712DomainChanged" | "HospitalRegistered" | "OwnershipTransferred" | "RelayerUpdated" | "RequestCancelled" | "RequestCreated" | "RequestExpired" | "RequestFulfilled" | "ResourceLocked"): EventFragment;

    encodeFunctionData(functionFragment: 'GOLDEN_TIME_DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'availableSlots', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'cancelRequest', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'eip712Domain', values?: undefined): string;
encodeFunctionData(functionFragment: 'expireIfOverdue', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fulfillRequest', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'getRequest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hospitalVerifiers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isRegisteredHospital', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isRequestActive', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'lockedSlots', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'nonces', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerHospital', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'requestAndLock', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, [BigNumberish, BigNumberish], [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], [BigNumberish, BigNumberish], [BigNumberish, BigNumberish, BigNumberish, BigNumberish], BytesLike]): string;
encodeFunctionData(functionFragment: 'requestCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'requests', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTrustedRelayer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalSlots', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'trustedRelayer', values?: undefined): string;
encodeFunctionData(functionFragment: 'usedRequestHash', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'GOLDEN_TIME_DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'availableSlots', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'eip712Domain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'expireIfOverdue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fulfillRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hospitalVerifiers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegisteredHospital', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRequestActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockedSlots', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nonces', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerHospital', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestAndLock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTrustedRelayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSlots', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'trustedRelayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usedRequestHash', data: BytesLike): Result;
  }

  
    export namespace EIP712DomainChangedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace HospitalRegisteredEvent {
      export type InputTuple = [hospital: AddressLike, verifier: AddressLike, totalSlots: BigNumberish];
      export type OutputTuple = [hospital: string, verifier: string, totalSlots: bigint];
      export interface OutputObject {hospital: string, verifier: string, totalSlots: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RelayerUpdatedEvent {
      export type InputTuple = [newRelayer: AddressLike];
      export type OutputTuple = [newRelayer: string];
      export interface OutputObject {newRelayer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestCancelledEvent {
      export type InputTuple = [requestId: BigNumberish];
      export type OutputTuple = [requestId: bigint];
      export interface OutputObject {requestId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestCreatedEvent {
      export type InputTuple = [requestId: BigNumberish, ambulanceOperator: AddressLike, hospital: AddressLike, ktasLevel: BigNumberish];
      export type OutputTuple = [requestId: bigint, ambulanceOperator: string, hospital: string, ktasLevel: bigint];
      export interface OutputObject {requestId: bigint, ambulanceOperator: string, hospital: string, ktasLevel: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestExpiredEvent {
      export type InputTuple = [requestId: BigNumberish];
      export type OutputTuple = [requestId: bigint];
      export interface OutputObject {requestId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestFulfilledEvent {
      export type InputTuple = [requestId: BigNumberish];
      export type OutputTuple = [requestId: bigint];
      export interface OutputObject {requestId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ResourceLockedEvent {
      export type InputTuple = [requestId: BigNumberish, hospital: AddressLike, deadline: BigNumberish];
      export type OutputTuple = [requestId: bigint, hospital: string, deadline: bigint];
      export interface OutputObject {requestId: bigint, hospital: string, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface GoldenLock extends BaseContract {
    
    connect(runner?: ContractRunner | null): GoldenLock;
    waitForDeployment(): Promise<this>;

    interface: GoldenLockInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    GOLDEN_TIME_DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    availableSlots: TypedContractMethod<
      [hospital: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    cancelRequest: TypedContractMethod<
      [requestId: BigNumberish, ambulanceSignature: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    eip712Domain: TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >
    

    
    expireIfOverdue: TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fulfillRequest: TypedContractMethod<
      [requestId: BigNumberish, hospitalSignature: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getRequest: TypedContractMethod<
      [requestId: BigNumberish, ],
      [GoldenLock.EmergencyRequestStructOutput],
      'view'
    >
    

    
    hospitalVerifiers: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    isRegisteredHospital: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isRequestActive: TypedContractMethod<
      [requestId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    lockedSlots: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    nonces: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerHospital: TypedContractMethod<
      [hospital: AddressLike, verifierAddress: AddressLike, slotCapacity: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    requestAndLock: TypedContractMethod<
      [hospital: AddressLike, ambulanceOperator: AddressLike, ktasLevel: BigNumberish, requestHash: BigNumberish, a: [BigNumberish, BigNumberish], b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], c: [BigNumberish, BigNumberish], publicSignals: [BigNumberish, BigNumberish, BigNumberish, BigNumberish], ambulanceSignature: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    requestCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    requests: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint] & {ambulanceOperator: string, hospital: string, ktasLevel: bigint, requestedAt: bigint, lockDeadline: bigint, status: bigint }],
      'view'
    >
    

    
    setTrustedRelayer: TypedContractMethod<
      [_relayer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalSlots: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    trustedRelayer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    usedRequestHash: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'GOLDEN_TIME_DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'availableSlots'): TypedContractMethod<
      [hospital: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelRequest'): TypedContractMethod<
      [requestId: BigNumberish, ambulanceSignature: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'eip712Domain'): TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'expireIfOverdue'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fulfillRequest'): TypedContractMethod<
      [requestId: BigNumberish, hospitalSignature: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRequest'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [GoldenLock.EmergencyRequestStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'hospitalVerifiers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isRegisteredHospital'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRequestActive'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lockedSlots'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nonces'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerHospital'): TypedContractMethod<
      [hospital: AddressLike, verifierAddress: AddressLike, slotCapacity: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestAndLock'): TypedContractMethod<
      [hospital: AddressLike, ambulanceOperator: AddressLike, ktasLevel: BigNumberish, requestHash: BigNumberish, a: [BigNumberish, BigNumberish], b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], c: [BigNumberish, BigNumberish], publicSignals: [BigNumberish, BigNumberish, BigNumberish, BigNumberish], ambulanceSignature: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'requests'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint] & {ambulanceOperator: string, hospital: string, ktasLevel: bigint, requestedAt: bigint, lockDeadline: bigint, status: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'setTrustedRelayer'): TypedContractMethod<
      [_relayer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalSlots'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'trustedRelayer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usedRequestHash'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'EIP712DomainChanged'): TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
getEvent(key: 'HospitalRegistered'): TypedContractEvent<HospitalRegisteredEvent.InputTuple, HospitalRegisteredEvent.OutputTuple, HospitalRegisteredEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RelayerUpdated'): TypedContractEvent<RelayerUpdatedEvent.InputTuple, RelayerUpdatedEvent.OutputTuple, RelayerUpdatedEvent.OutputObject>;
getEvent(key: 'RequestCancelled'): TypedContractEvent<RequestCancelledEvent.InputTuple, RequestCancelledEvent.OutputTuple, RequestCancelledEvent.OutputObject>;
getEvent(key: 'RequestCreated'): TypedContractEvent<RequestCreatedEvent.InputTuple, RequestCreatedEvent.OutputTuple, RequestCreatedEvent.OutputObject>;
getEvent(key: 'RequestExpired'): TypedContractEvent<RequestExpiredEvent.InputTuple, RequestExpiredEvent.OutputTuple, RequestExpiredEvent.OutputObject>;
getEvent(key: 'RequestFulfilled'): TypedContractEvent<RequestFulfilledEvent.InputTuple, RequestFulfilledEvent.OutputTuple, RequestFulfilledEvent.OutputObject>;
getEvent(key: 'ResourceLocked'): TypedContractEvent<ResourceLockedEvent.InputTuple, ResourceLockedEvent.OutputTuple, ResourceLockedEvent.OutputObject>;

    filters: {
      
      'EIP712DomainChanged()': TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
      EIP712DomainChanged: TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
    

      'HospitalRegistered(address,address,uint256)': TypedContractEvent<HospitalRegisteredEvent.InputTuple, HospitalRegisteredEvent.OutputTuple, HospitalRegisteredEvent.OutputObject>;
      HospitalRegistered: TypedContractEvent<HospitalRegisteredEvent.InputTuple, HospitalRegisteredEvent.OutputTuple, HospitalRegisteredEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RelayerUpdated(address)': TypedContractEvent<RelayerUpdatedEvent.InputTuple, RelayerUpdatedEvent.OutputTuple, RelayerUpdatedEvent.OutputObject>;
      RelayerUpdated: TypedContractEvent<RelayerUpdatedEvent.InputTuple, RelayerUpdatedEvent.OutputTuple, RelayerUpdatedEvent.OutputObject>;
    

      'RequestCancelled(uint256)': TypedContractEvent<RequestCancelledEvent.InputTuple, RequestCancelledEvent.OutputTuple, RequestCancelledEvent.OutputObject>;
      RequestCancelled: TypedContractEvent<RequestCancelledEvent.InputTuple, RequestCancelledEvent.OutputTuple, RequestCancelledEvent.OutputObject>;
    

      'RequestCreated(uint256,address,address,uint8)': TypedContractEvent<RequestCreatedEvent.InputTuple, RequestCreatedEvent.OutputTuple, RequestCreatedEvent.OutputObject>;
      RequestCreated: TypedContractEvent<RequestCreatedEvent.InputTuple, RequestCreatedEvent.OutputTuple, RequestCreatedEvent.OutputObject>;
    

      'RequestExpired(uint256)': TypedContractEvent<RequestExpiredEvent.InputTuple, RequestExpiredEvent.OutputTuple, RequestExpiredEvent.OutputObject>;
      RequestExpired: TypedContractEvent<RequestExpiredEvent.InputTuple, RequestExpiredEvent.OutputTuple, RequestExpiredEvent.OutputObject>;
    

      'RequestFulfilled(uint256)': TypedContractEvent<RequestFulfilledEvent.InputTuple, RequestFulfilledEvent.OutputTuple, RequestFulfilledEvent.OutputObject>;
      RequestFulfilled: TypedContractEvent<RequestFulfilledEvent.InputTuple, RequestFulfilledEvent.OutputTuple, RequestFulfilledEvent.OutputObject>;
    

      'ResourceLocked(uint256,address,uint256)': TypedContractEvent<ResourceLockedEvent.InputTuple, ResourceLockedEvent.OutputTuple, ResourceLockedEvent.OutputObject>;
      ResourceLocked: TypedContractEvent<ResourceLockedEvent.InputTuple, ResourceLockedEvent.OutputTuple, ResourceLockedEvent.OutputObject>;
    
    };
  }