/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface VerifierInterface extends Interface {
    getFunction(nameOrSignature: "forceInvalid" | "setForceInvalid" | "verifyProof"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MockVerifyCalled"): EventFragment;

    encodeFunctionData(functionFragment: 'forceInvalid', values?: undefined): string;
encodeFunctionData(functionFragment: 'setForceInvalid', values: [boolean]): string;
encodeFunctionData(functionFragment: 'verifyProof', values: [[BigNumberish, BigNumberish], [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], [BigNumberish, BigNumberish], [BigNumberish, BigNumberish, BigNumberish, BigNumberish]]): string;

    decodeFunctionResult(functionFragment: 'forceInvalid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setForceInvalid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyProof', data: BytesLike): Result;
  }

  
    export namespace MockVerifyCalledEvent {
      export type InputTuple = [canAccept: BigNumberish, requiredBeds: BigNumberish, requiredSpecialists: BigNumberish, result: boolean];
      export type OutputTuple = [canAccept: bigint, requiredBeds: bigint, requiredSpecialists: bigint, result: boolean];
      export interface OutputObject {canAccept: bigint, requiredBeds: bigint, requiredSpecialists: bigint, result: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Verifier extends BaseContract {
    
    connect(runner?: ContractRunner | null): Verifier;
    waitForDeployment(): Promise<this>;

    interface: VerifierInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    forceInvalid: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    setForceInvalid: TypedContractMethod<
      [_forceInvalid: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    verifyProof: TypedContractMethod<
      [arg0: [BigNumberish, BigNumberish], arg1: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], arg2: [BigNumberish, BigNumberish], input: [BigNumberish, BigNumberish, BigNumberish, BigNumberish], ],
      [boolean],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'forceInvalid'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setForceInvalid'): TypedContractMethod<
      [_forceInvalid: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyProof'): TypedContractMethod<
      [arg0: [BigNumberish, BigNumberish], arg1: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], arg2: [BigNumberish, BigNumberish], input: [BigNumberish, BigNumberish, BigNumberish, BigNumberish], ],
      [boolean],
      'nonpayable'
    >;

    getEvent(key: 'MockVerifyCalled'): TypedContractEvent<MockVerifyCalledEvent.InputTuple, MockVerifyCalledEvent.OutputTuple, MockVerifyCalledEvent.OutputObject>;

    filters: {
      
      'MockVerifyCalled(uint256,uint256,uint256,bool)': TypedContractEvent<MockVerifyCalledEvent.InputTuple, MockVerifyCalledEvent.OutputTuple, MockVerifyCalledEvent.OutputObject>;
      MockVerifyCalled: TypedContractEvent<MockVerifyCalledEvent.InputTuple, MockVerifyCalledEvent.OutputTuple, MockVerifyCalledEvent.OutputObject>;
    
    };
  }