// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IGroth16Verifier$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IGroth16Verifier";
  readonly sourceName: "contracts/interfaces/IGroth16Verifier.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256[2]","name":"a","type":"uint256[2]"},{"internalType":"uint256[2][2]","name":"b","type":"uint256[2][2]"},{"internalType":"uint256[2]","name":"c","type":"uint256[2]"},{"internalType":"uint256[4]","name":"input","type":"uint256[4]"}],"name":"verifyProof","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IGroth16Verifier.sol";
  readonly buildInfoId: "solc-0_8_24-2ec4a0dac5d5e4c04e5bb9e028d5d150788474f8";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IGroth16Verifier"]: IGroth16Verifier$Type;
    ["contracts/interfaces/IGroth16Verifier.sol:IGroth16Verifier"]: IGroth16Verifier$Type;
  }
}