// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IGroth16Verifier$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IGroth16Verifier";
  readonly sourceName: "contracts/Verifier.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256[2]","name":"a","type":"uint256[2]"},{"internalType":"uint256[2][2]","name":"b","type":"uint256[2][2]"},{"internalType":"uint256[2]","name":"c","type":"uint256[2]"},{"internalType":"uint256[3]","name":"input","type":"uint256[3]"}],"name":"verifyProof","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/Verifier.sol";
  readonly buildInfoId: "solc-0_8_24-69a97f0f823d4c5b9f2bd0fe5b2f2c7ec3f0d19e";
};

export interface Verifier$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Verifier";
  readonly sourceName: "contracts/Verifier.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256[2]","name":"a","type":"uint256[2]"},{"internalType":"uint256[2][2]","name":"b","type":"uint256[2][2]"},{"internalType":"uint256[2]","name":"c","type":"uint256[2]"},{"internalType":"uint256[3]","name":"input","type":"uint256[3]"}],"name":"verifyProof","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"pure","type":"function"}];
  readonly bytecode: "0x608060405234801561000f575f80fd5b5060f88061001c5f395ff3fe6080604052348015600e575f80fd5b50600436106026575f3560e01c806311479fea14602a575b5f80fd5b603f60353660046068565b6001949350505050565b604051901515815260200160405180910390f35b80604081018310156062575f80fd5b92915050565b5f805f80610160808688031215607c575f80fd5b608487876053565b945060c08601878111156095575f80fd5b60408701945060a388826053565b93505086818701111560b3575f80fd5b5092959194509261010001915056fea2646970667358221220dfe13ff8beea59a8298d4caea35d0f73662c77af930a174ae161c53190f8912264736f6c63430008180033";
  readonly deployedBytecode: "0x6080604052348015600e575f80fd5b50600436106026575f3560e01c806311479fea14602a575b5f80fd5b603f60353660046068565b6001949350505050565b604051901515815260200160405180910390f35b80604081018310156062575f80fd5b92915050565b5f805f80610160808688031215607c575f80fd5b608487876053565b945060c08601878111156095575f80fd5b60408701945060a388826053565b93505086818701111560b3575f80fd5b5092959194509261010001915056fea2646970667358221220dfe13ff8beea59a8298d4caea35d0f73662c77af930a174ae161c53190f8912264736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/Verifier.sol";
  readonly buildInfoId: "solc-0_8_24-69a97f0f823d4c5b9f2bd0fe5b2f2c7ec3f0d19e";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IGroth16Verifier"]: IGroth16Verifier$Type
    ["Verifier"]: Verifier$Type;
    ["contracts/Verifier.sol:IGroth16Verifier"]: IGroth16Verifier$Type
    ["contracts/Verifier.sol:Verifier"]: Verifier$Type;
  }
}