// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MockVerifier$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockVerifier";
  readonly sourceName: "contracts/mocks/MockVerifier.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"canAccept","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"requiredBeds","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"requiredSpecialists","type":"uint256"},{"indexed":false,"internalType":"bool","name":"result","type":"bool"}],"name":"MockVerifyCalled","type":"event"},{"inputs":[],"name":"forceInvalid","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bool","name":"_forceInvalid","type":"bool"}],"name":"setForceInvalid","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256[2]","name":"","type":"uint256[2]"},{"internalType":"uint256[2][2]","name":"","type":"uint256[2][2]"},{"internalType":"uint256[2]","name":"","type":"uint256[2]"},{"internalType":"uint256[4]","name":"input","type":"uint256[4]"}],"name":"verifyProof","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x6080806040523461001657610160908161001b8239f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c9081633eabe1771461010c575080634621fce4146100de57635fe8c13b1461003d575f80fd5b346100da576101803660031901126100da57366044116100da573660c4116100da576101043681116100da5736610184116100da5760209060ff5f541615806100cf575b60807febab5c934b3c32dda6215d475929b0708107f81f98075cd32fdcd705f380e69591604051933584526101243585850152610144356040850152151592836060820152a1604051908152f35b508035600114610081565b5f80fd5b346100da5760203660031901126100da576004358015158091036100da5760ff80195f54169116175f555f80f35b346100da575f3660031901126100da5760209060ff5f541615158152f3fea2646970667358221220217cf9bb84b48d05dcb528cb2c82ee1bc28d0516566252bdd5cba8e52938c9de64736f6c63430008180033";
  readonly deployedBytecode: "0x6080806040526004361015610012575f80fd5b5f3560e01c9081633eabe1771461010c575080634621fce4146100de57635fe8c13b1461003d575f80fd5b346100da576101803660031901126100da57366044116100da573660c4116100da576101043681116100da5736610184116100da5760209060ff5f541615806100cf575b60807febab5c934b3c32dda6215d475929b0708107f81f98075cd32fdcd705f380e69591604051933584526101243585850152610144356040850152151592836060820152a1604051908152f35b508035600114610081565b5f80fd5b346100da5760203660031901126100da576004358015158091036100da5760ff80195f54169116175f555f80f35b346100da575f3660031901126100da5760209060ff5f541615158152f3fea2646970667358221220217cf9bb84b48d05dcb528cb2c82ee1bc28d0516566252bdd5cba8e52938c9de64736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/mocks/MockVerifier.sol";
  readonly buildInfoId: "solc-0_8_24-2ec4a0dac5d5e4c04e5bb9e028d5d150788474f8";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MockVerifier"]: MockVerifier$Type;
    ["contracts/mocks/MockVerifier.sol:MockVerifier"]: MockVerifier$Type;
  }
}