/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as verifierSol from './Verifier.sol/index.js';
export { GoldenLock__factory } from './GoldenLock__factory.js';