/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { Verifier, VerifierInterface } from "../Verifier.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256[2]",
        "name": "a",
        "type": "uint256[2]"
      },
      {
        "internalType": "uint256[2][2]",
        "name": "b",
        "type": "uint256[2][2]"
      },
      {
        "internalType": "uint256[2]",
        "name": "c",
        "type": "uint256[2]"
      },
      {
        "internalType": "uint256[4]",
        "name": "input",
        "type": "uint256[4]"
      }
    ],
    "name": "verifyProof",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x60808060405234601457609490816100198239f35b5f80fdfe60808060405260043610156011575f80fd5b5f3560e01c635fe8c13b146023575f80fd5b34605a57610180366003190112605a5736604411605a573660c411605a573661010411605a573661018411605a5780600160209252f35b5f80fdfea264697066735822122064c98719c3669e4f85ea882b4429cadd16931e88a22a29b1579fce948dae36e864736f6c63430008180033";

  
      type VerifierConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: VerifierConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Verifier__factory extends ContractFactory {
    
      constructor(...args: VerifierConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Verifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Verifier__factory {
      return super.connect(runner) as Verifier__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): VerifierInterface {
      return new Interface(_abi) as VerifierInterface;
    }
    
    override attach(address: string | Addressable): Verifier {
      return super.attach(address) as Verifier;
    }
  static connect(address: string, runner?: ContractRunner | null): Verifier {
      return new Contract(address, _abi, runner) as unknown as Verifier;
    }
  }

  
  