/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { Verifier, VerifierInterface } from "../Verifier.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "canAccept",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "requiredBeds",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "requiredSpecialists",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "result",
        "type": "bool"
      }
    ],
    "name": "MockVerifyCalled",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "forceInvalid",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bool",
        "name": "_forceInvalid",
        "type": "bool"
      }
    ],
    "name": "setForceInvalid",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256[2]",
        "name": "",
        "type": "uint256[2]"
      },
      {
        "internalType": "uint256[2][2]",
        "name": "",
        "type": "uint256[2][2]"
      },
      {
        "internalType": "uint256[2]",
        "name": "",
        "type": "uint256[2]"
      },
      {
        "internalType": "uint256[4]",
        "name": "input",
        "type": "uint256[4]"
      }
    ],
    "name": "verifyProof",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080806040523461001657610160908161001b8239f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c9081633eabe1771461010c575080634621fce4146100de57635fe8c13b1461003d575f80fd5b346100da576101803660031901126100da57366044116100da573660c4116100da576101043681116100da5736610184116100da5760209060ff5f541615806100cf575b60807febab5c934b3c32dda6215d475929b0708107f81f98075cd32fdcd705f380e69591604051933584526101243585850152610144356040850152151592836060820152a1604051908152f35b508035600114610081565b5f80fd5b346100da5760203660031901126100da576004358015158091036100da5760ff80195f54169116175f555f80f35b346100da575f3660031901126100da5760209060ff5f541615158152f3fea2646970667358221220c294e929ccb33a9bec6f1ed7ea70e55d9951f28e329ca458a4b16539ed84457b64736f6c63430008180033";

  
      type VerifierConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: VerifierConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Verifier__factory extends ContractFactory {
    
      constructor(...args: VerifierConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Verifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Verifier__factory {
      return super.connect(runner) as Verifier__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): VerifierInterface {
      return new Interface(_abi) as VerifierInterface;
    }
    
    override attach(address: string | Addressable): Verifier {
      return super.attach(address) as Verifier;
    }
  static connect(address: string, runner?: ContractRunner | null): Verifier {
      return new Contract(address, _abi, runner) as unknown as Verifier;
    }
  }

  
  